project:
  type: website
  output-dir: docs

website:
  title: "MPI-Bibliothek"
  description: "Dashboard für Erwerbungen & Bestandsanalyse der MPI-Bibliothek"
  
  navbar:
    background: primary
    search: false
    left:
      - href: index.qmd
        text: "Einleitung"
      - href: bestand.qmd
        text: "Bestand"
      - href: erwerbungen.qmd  
        text: "Erwerbungen"
    
    right:
      - icon: github
        href: https://github.com/thomasgerdes/library-statistics
        aria-label: "GitHub Repository"

  sidebar: false
  
  page-footer:
    left: "© 2025 [Thomas Gerdes](https://thomasgerdes.de){target=\"_blank\"}"

format:
  html:
    theme: cosmo
    css: shared/styles.css
    toc: true
    toc-location: left
    toc-depth: 3
    code-fold: true
    code-tools: false
    embed-resources: false
    page-layout: full
    lang: de
    
    include-in-header:
      - text: |
          <meta name="author" content="Thomas Gerdes">
          <meta name="description" content="Dashboard for MPI Library statistics and analysis">
          <meta name="keywords" content="library, statistics, dashboard, acquisitions, collection, MPI, MPG">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.9.1/chart.min.js"></script>
          <title>MPI-Bibliothek</title>

execute:
  echo: false
  warning: false
  error: false

editor: visual